### ISSUE TITLE
Crash on Nexus 4

### ISSUE THREAD

**Issue by yangshulin2019** [lukhnos/LuceneSearchDemo-Android#5]
I have successfully made Lucene run on android, thanks for your project. But when I run it on some devices, the index will be problem and crash the app. I don't know how to fix it. May be it is a problem by the thread conflict or NIO?

Device: Genymotion Nexus 4 virtual machine. Android OS 4.4

The stack track data is below:
```
java.lang.ArrayIndexOutOfBoundsException: length=5; index=5767169
     at org.apache.lucene.util.FixedBitSet.set(FixedBitSet.java:193)
     at org.apache.lucene.codecs.PushPostingsWriterBase.writeTerm(PushPostingsWriterBase.java:155)
     at org.apache.lucene.codecs.blocktree.BlockTreeTermsWriter$TermsWriter.write(BlockTreeTermsWriter.java:1041)
     at org.apache.lucene.codecs.blocktree.BlockTreeTermsWriter.write(BlockTreeTermsWriter.java:456)
     at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat$FieldsWriter.write(PerFieldPostingsFormat.java:198)
     at org.apache.lucene.index.FreqProxTermsWriter.flush(FreqProxTermsWriter.java:107)
     at org.apache.lucene.index.DefaultIndexingChain.flush(DefaultIndexingChain.java:112)
     at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:426)
     at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:507)
     at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:619)
     at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:2845)
     at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:3011)
     at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:2976)
     at org.GodFootSteps.book.lucene.BookIndexCore.replaceBookIndex(BookIndexCore.java:131)
     at org.GodFootSteps.book.lucene.BookIndexService.doReplaceIndex(BookIndexService.java:156)
     at org.GodFootSteps.book.lucene.BookIndexService.onHandleIntent(BookIndexService.java:88)
     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:136)
     at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by lukhnos** [comment]
It's been a while since I worked on the project. What I can offer is some debugging tips.

First I would rule out NIO issues since the stack trace does not seem IO-related. I would in general rule out threading issues first since Mobile Lucene is based on Lucene 5, which had been very much battle-tested as server-side software (ElasticSearch, Solr)—not to say it's impossible, just that we are trying to have a small search space (no pun intended) to begin with.

I would strongly encourage you to add debug logging (even just `System.err.println`!) in `FixedBitSet.java`. The stack trace ends up here:

https://github.com/lukhnos/mobilelucene/blob/master/lucene/core/src/java/org/apache/lucene/util/FixedBitSet.java#L193

There are a number of places that set the `bits` field. You can find all those by looking for `bits =` in the code. Put debug there and print the length of the arrays given (you probably also want to print the object reference via `System.identityHashCode()` to know where you get the bits). I wouldn't be surprised if for some reason the `bits` field is created with a smaller capacity.

I also noticed in your stack trace that you seem to be replacing the index (`replaceBookIndex`). Since that's your code I don't know how you "replace" the index. I don't call a good way to replace a Lucene index in place, other than writing a new one and having your query client use the new index. So I would also look into the possibility that you are doing some Lucene operations that aren't well-supported (or poorly documented) by Lucene.

One last thing: if you don't need to use Lucene 5, Lucene 3.x (I forget the exact value for `x`) is the last version that does not use any Java NIO API and can work on Android 4.x without any modification.
