### ISSUE TITLE
Android Error: An SPI class of type org.apache.lucene.codecs.PostingsFormat with classname org.apache.lucene.codecs.lucene50.Lucene50PostingsFormat does not exist 

### ISSUE THREAD

**Issue by dejanyan** [lukhnos/LuceneSearchDemo-Android#7]
java.util.ServiceConfigurationError: An SPI class of type org.apache.lucene.codecs.PostingsFormat with classname org.apache.lucene.codecs.lucene50.Lucene50PostingsFormat does not exist.
        at org.apache.lucene.util.SPIClassIterator.next(SPIClassIterator.java:265)
        at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:65)
        at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:47)
        at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:37)
        at org.apache.lucene.codecs.PostingsFormat$Holder.<clinit>(PostingsFormat.java:49)
        at org.apache.lucene.codecs.PostingsFormat$Holder.getLoader(PostingsFormat.java:54)
        at org.apache.lucene.codecs.PostingsFormat.forName(PostingsFormat.java:112)
        at org.apache.lucene.codecs.lucene53.Lucene53Codec.<init>(Lucene53Codec.java:160)
        at org.apache.lucene.codecs.lucene53.Lucene53Codec.<init>(Lucene53Codec.java:80)
        at java.lang.Class.newInstance(Native Method)
        at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:67)
        at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:45)
        at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:37)
        at org.apache.lucene.codecs.Codec$Holder.<clinit>(Codec.java:47)
        at org.apache.lucene.codecs.Codec.getDefault(Codec.java:140)
        at org.apache.lucene.index.LiveIndexWriterConfig.<init>(LiveIndexWriterConfig.java:120)
        at org.apache.lucene.index.IndexWriterConfig.<init>(IndexWriterConfig.java:140)

**Comment by lukhnos** [comment]
This project has been long dormant and I'm going to archive it. This looks like an error where Lucene could not find a matching codec, which in turn may be a symptom of missing classes, especially if the dexing step stripped the required classes over-aggressively. That's all I can say.
